#!/bin/bash
rm -f *.txt
function ta_macd_ext {
for i in {1..10}
#for i in SMA EMA WMA DEMA TEMA TRIMA KAMA MAMA T3
#for i in 10 20 30 40 50 60 70 80 90 100
#for i in 1m 2m 3m 5m 15m 30m 45m 1h 4h  
do
zenbot sim binance.ENJ-BTC  \
--strategy=multi \
--period_length=2m \
--order_adjust_time=2000 \
--order_poll_time=5000 \
--poll_trades=1000 \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=77\
--length=10 \
--fish_pct_change=0 \
--pos_length=1 \
--src=ohlc4 \
--momentum_size=5 \
--max_sell_loss_pct=2 \
--profit_stop_enable_pct=0 \
--profit_stop_pct=0 \
--markdown_buy_pct=0.30 \
--markup_sell_pct=0.31 \
--sell_pct=100 --buy_pct=100 --currency_capital=0.08 --days=2 | grep -A5 "end balance" > $i.txt
done
}
ta_macd_ext
#31 34
