#!/bin/bash
rm -f *.txt
function macd {
#for i in {1..25}
for i in {10..40}
#for i in  10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 00
#for i in 10s 1m 2m 3m 4m 5m 10m 15m 30m 45m 1h 2h 3h 4h
do
zenbot sim  gdax.LTC-USD  \
--strategy=macd \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=25 \
--overbought_rsi=75 \
--poll_trades=3000 \
--currency_capital=460 \
--days=8 \
--buy_stop_pct=0 \
--sell_stop_pct=2.5 \
--max_sell_loss_pct=3 \
--profit_stop_enable_pct=5 \
--exact_buy_orders  \
--exact_sell_orders  \
--profit_stop_pct=0.5 \
--sell_pct=99 \
--buy_pct=99 \
--markdown_buy_pct=0.$i \
--markup_sell_pct=0.$i | grep -A5 "end balance" > $i.txt
done 
}
macd
