#!/bin/bash
rm -f *.txt
function ta_macd_ext {
#for i in {1..9}
#for i in 10 20 30 40 50 60 70 80 90 100
#for i in 1m 3m 5m 15m 30m 45m 1h 4h
for i in `cat ./stg.ini`
do
zenbot sim binance.BTT-BTC  \
--strategy=$i \
--period=1h \
--exact_buy_orders \
--exact_sell_orders \
--buy_pct=100 --sell_pct=100 --currency_capital=0.08 --days=7 | grep -A5 "end balance" > $i.txt
done
}
#18 16
ta_macd_ext
