#!/bin/bash
rm -f *.txt
function macd {
for i in {5..10}
#for i in {10..30}
#for i in  10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 00
#for i in 10s 1m 2m 3m 4m 5m 10m 15m 30m 45m 1h 2h 3h 4h
do
zenbot sim binance.LTC-BTC \
--strategy=macd \
--exact_buy_orders \
--exact_sell_orders \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=20 \
--overbought_rsi=76 \
--poll_trades=3000 \
--sell_stop_pct=0 \
--buy_stop_pct=0 \
--order_poll_time=5000 \
--order_adjust_time=5000 \
--max_sell_loss_pct=2 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=2 \
--profit_stop_pct=0.6 \
--max_slippage_pct=9 \
--order_adjust_time=5000 \
--markdown_buy_pct=0.23 \
--markup_sell_pct=0.23 --currency_capital=0.06 --sell_pct=99 --buy_pct=99  --days=7 | grep -A5 "end balance" > $i.txt
done
}
#srsi_macd
macd
#--markdown_buy_pct=0.66 
#--markup_sell_pct=0.32 36
###### 
#--markdown_buy_pct=0.50
#--markup_sell_pct=0.32
