#!/bin/bash
rm -f *.txt
function ta_macd_ext {
for i in {30..50}
#for i in SMA EMA WMA DEMA TEMA TRIMA KAMA MAMA T3
#for i in 10 20 30 40 50 60 70 80 90 100
#for i in 1m 3m 5m 15m 30m 45m 1h 4h  
do
zenbot sim binance.RVN-BTC  \
--strategy=multi \
--period_length=3m \
--poll_trades=5000 \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--length=11 \
--fish_pct_change=0 \
--pos_length=2 \
--src=ohlc4 \
--momentum_size=7 \
--max_sell_loss_pct=3 \
--profit_stop_enable_pct=4 \
--markdown_buy_pct=0.31 \
--markup_sell_pct=0.$i \
--sell_pct=100 --buy_pct=100 --currency_capital=0.08 --days=2 --end=201903070800  | grep -A5 "end balance" > $i.txt
done
}
ta_macd_ext
#31 34
