#!/bin/bash
rm -f *.txt
function ta_macd_ext {
for i in {1..10}
#for i in SMA EMA WMA DEMA TEMA TRIMA KAMA MAMA T3
#for i in 10 20 30 40 50 60 70 80 90 100
#for i in 1m 3m 5m 15m 30m 45m 1h 4h  
do
zenbot sim binance.RVN-BTC  \
--strategy=ta_macd_ext \
--period=3m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--fast_ma_type=EMA \
--slow_ma_type=EMA \
--signal_ma_type=EMA \
--default_ma_type=signal_ma_type \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--poll_trades=2000 \
--order_poll_time=5000 \
--order_adjust_time=1000 \
--sell_stop_pct=0 \
--buy_stop_pct=0 \
--max_sell_loss_pct=4 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=0 \
--max_slippage_pct=25 \
--profit_stop_pct=0 \
--markdown_buy_pct=0.31 \
--markup_sell_pct=0.85 --sell_pct=100 --buy_pct=100 --currency_capital=0.08 --days=3  --end=201903080900  | grep -A5 "end balance" > $i.txt
done
}
#SELL 16
#18 16
ta_macd_ext
