#!/bin/bash
rm -f *.txt
function ta_macd_ext {
for i in {1..10}
#for i in SMA EMA WMA DEMA TEMA TRIMA KAMA MAMA T3
#for i in 10 20 30 40 50 60 70 80 90 100
#for i in 1m 3m 5m 15m 30m 45m 60m
do
zenbot sim binance.TRX-BTC  \
--strategy=multi \
--period_length=15m \
--min_periods=52 \
--markdown_buy_pct=0 \
--markup_sell_pct=0 \
--overbought_rsi_periods=25 \
--overbought_rsi=70 \
--length=5 \
--fish_pct_change=0 \
--pos_length=1 \
--src=ohlc4 \
--momentum_size=9 \
--max_sell_loss_pct=5 \
--profit_stop_enable_pct=0 \
--markdown_buy_pct=0.3 \
--markup_sell_pct=0.3 \
--sell_pct=100 --buy_pct=100 --currency_capital=0.08 --days=7 | grep -A5 "end balance" > $i.txt
done
}
#SELL 16
#18 16
ta_macd_ext


