#!/bin/bash
rm -f *.txt
function macd {
for i in {0..9}
#for i in {20..30}
#for i in  10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 00
#for i in 10s 1m 2m 3m 4m 5m 10m 15m 30m 45m 1h 2h 3h 4h
do
zenbot sim binance.TRX-BTC  \
--strategy=trix_max \
--period=3m \
--min_periods=52 \
--exact_buy_orders \
--exact_sell_orders \
--order_adjust_time=4000 \
--max_sell_loss_pct=25 \
--max_buy_loss_pct=100 \
--max_slippage_pct=20 \
--profit_stop_enable_pct=0 \
--profit_stop_pct=0 \
--markdown_buy_pct=0.$i \
--markup_sell_pct=0.$i --currency_capital=0.015 --sell_pct=100 --buy_pct=100  --days=7 | grep -A5 "end balance" > $i.txt
# 54 49
done
}
#srsi_macd
macd
#--markdown_buy_pct=0.66 
#--markup_sell_pct=0.32 36
###### 
#--markdown_buy_pct=0.50
#--markup_sell_pct=0.32
