#!/bin/bash
#rm -f *.txt
function ta_macd_ext {
for i in {10..30}
#for i in 10 20 30 40 50 60 70 80 90 100
#for i in 1m 2m 3m 4m  5m 6m 7m 8m 9m 10m 15m 30m 45m 60m
do
zenbot sim binance.CMT-BTC  \
--strategy=ta_macd_ext \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--fast_ma_type=EMA \
--slow_ma_type=EMA \
--signal_ma_type=EMA \
--default_ma_type=signal_ma_type \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=25 \
--overbought_rsi=70 \
--poll_trades=3000 \
--order_poll_time=5000 \
--exact_buy_orders \
--exact_sell_orders \
--order_adjust_time=5000 \
--sell_stop_pct=0 \
--buy_stop_pct=0 \
--max_sell_loss_pct=4 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=4 \
--max_slippage_pct=5 \
--profit_stop_pct=0.1 \
--markdown_buy_pct=0.$i \
--markup_sell_pct=0.$i --buy_pct=100 --sell_pct=100 --currency_capital=0.02 --days=3 | grep -A5 "end balance" > $i.txt
done
}
#18 16
ta_macd_ext
