#!/bin/bash
rm -f *.txt
function single {
for i in {1..9}
#for i in {10..50}
#for i in {40..70}
#for i in  10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 00
#for i in 10s 1m 2m 3m 4m 5m 10m 15m 30m 35m 45m 1h 2h 3h 4h 
do
zenbot sim  binance.XVG-BTC  \
--strategy=macd \
--period=3m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=1.1 \
--overbought_rsi_periods=20 \
--overbought_rsi=73 \
--poll_trades=3000 \
--exact_buy_orders \
--exact_sell_orders \
--sell_stop_pct=6 \
--currency_capital=0.06 \
--days=8 \
--max_sell_loss_pct=6 \
--profit_stop_enable_pct=14 \
--profit_stop_pct=1 \
--sell_pct=100 \
--buy_pct=100 \
--markdown_buy_pct=0.82 \
--markup_sell_pct=0.25 | grep -A5 "end balance" > $i.txt
done
}

function multi {
#for i in {1..9}
for i in {10..50}
#for i in  10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 00
do
zenbot sim  binance.XVG-BTC  \
--strategy=macd \
--period=3m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=20 \
--overbought_rsi=75 \
--poll_trades=3000 \
--exact_buy_orders \
--exact_sell_orders \
--currency_capital=0.06 \
--days=7 \
--max_sell_loss_pct=3 \
--max_buy_loss_pct=1.$i \
--profit_stop_enable_pct=7 \
--profit_stop_pct=0.5 \
--sell_pct=99 \
--buy_pct=99 \
--markdown_buy_pct=0.47 \
--markup_sell_pct=0.42 | grep -A5 "end balance" > 1.$i.txt

zenbot sim  binance.XVG-BTC  \
--strategy=macd \
--period=3m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=20 \
--overbought_rsi=75 \
--poll_trades=3000 \
--exact_buy_orders \
--exact_sell_orders \
--currency_capital=0.06 \
--days=7 \
--max_sell_loss_pct=3 \
--max_buy_loss_pct=2.$i \
--profit_stop_enable_pct=7 \
--profit_stop_pct=0.5 \
--sell_pct=99 \
--buy_pct=99 \
--markdown_buy_pct=0.47 \
--markup_sell_pct=0.42 | grep -A5 "end balance" > 2.$i.txt

zenbot sim  binance.XVG-BTC  \
--strategy=macd \
--period=3m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=20 \
--overbought_rsi=75 \
--poll_trades=3000 \
--exact_buy_orders \
--exact_sell_orders \
--currency_capital=0.06 \
--days=7 \
--max_sell_loss_pct=3 \
--max_buy_loss_pct=3.$i \
--profit_stop_enable_pct=7 \
--profit_stop_pct=0.5 \
--sell_pct=99 \
--buy_pct=99 \
--markdown_buy_pct=0.47 \
--markup_sell_pct=0.42 | grep -A5 "end balance" > 3.$i.txt

done
}


single
#multi
