#!/bin/bash
rm -f *.txt
function single {
#for i in {1..9}
#for i in {10..20}
for i in {60..90}
#for i in  10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 00
#for i in 10s 1m 2m 3m 4m 5m 10m 15m 30m 35m 45m 1h 2h 3h 4h 
do
zenbot sim \
binance.XVG-BTC  \
--strategy=macd \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=20 \
--overbought_rsi=73 \
--poll_trades=3000 \
--currency_capital=0.06 \
--max_sell_loss_pct=4  \
--exact_buy_orders \
--exact_sell_orders \
--sell_stop_pct=3 \
--buy_stop_pct=0 \
--profit_stop_enable_pct=6 \
--profit_stop_pct=0.1 \
--markdown_buy_pct=0.47 \
--markup_sell_pct=0.22 --currency_capital=0.06 --sell_pct=100 --buy_pct=100  --days=7  | grep -A5 "end balance" > $i.txt
done
}
#55 47
single
