#!/bin/bash
rm -f *.txt
function macd {
#for i in {1..9}
for i in {20..60}
#for i in  10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 00
#for i in 10s 1m 2m 3m 4m 5m 10m 15m 30m 45m 1h 2h 3h 4h
do
zenbot sim binance.STORM-BTC  \
--strategy=macd \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=27 \
--overbought_rsi=75 \
--poll_trades=3000 \
--exact_buy_orders \
--exact_sell_orders \
--sell_stop_pct=3 \
--buy_stop_pct=2 \
--max_sell_loss_pct=1 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=9 \
--profit_stop_pct=0.5 \
--max_slippage_pct=3 \
--markdown_buy_pct=0.54 \
--order_adjust_time=5000 \
--markup_sell_pct=0.46 --currency_capital=0.06 --sell_pct=100 --buy_pct=100  --days=7 | grep -A5 "end balance" > $i.txt
done
}
#srsi_macdA
macd
#--markdown_buy_pct=0.66 
#--markup_sell_pct=0.32 36
###### 
#--markdown_buy_pct=0.50
#--markup_sell_pct=0.32
